dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
language: r
r: 3.5.0
r: bioc-release
sudo: false
bioc_required: true
warnings_are_errors: false


addons:
  apt:
    packages:
      - libv8-3.14-dev
      

# Install packrat if needed and have it restore packages.
install:
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - Rscript -e 'source(file = "http://bioconductor.org/biocLite.R");tryCatch(useDevel(devel = TRUE), error = function(err){message(err)})'
  #- R -e 'if (system.file(package="BiocInstaller") == "") install.packages("BiocInstaller")'
  #- R -e  "source('https://bioconductor.org/biocLite.R');biocLite('BiocGenerics');"
  #- R -e "options(repos = c(getOption('repos'), BiocInstaller::biocinstallRepos()));"
  #- R -e  "source('https://bioconductor.org/biocLite.R');biocLite(c('BiocGenerics', 'Biobase' ,'IRanges' ,'S4Vectors', 'AnnotationDbiannotate' ,'GSEABase', 'genefilter' ,'graph', 'RBGL', 'AnnotationForge',' Category' ,'GO.db','Rgraphviz','org.Mm.eg.db',' RDAVIDWebService' ));"
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::packify(); packrat::restore()"
  #- R -e  "source('https://bioconductor.org/biocLite.R');biocLite(c('BiocGenerics', 'Biobase' ,'IRanges' ,'S4Vectors', 'AnnotationDbiannotate' ,'GSEABase', 'genefilter' ,'graph', 'RBGL', 'AnnotationForge',' Category' ,'GO.db','Rgraphviz','org.Mm.eg.db',' RDAVIDWebService' ));"
  # - R -e "0" --args --bootstrap-packrat


cache:
  packages: true
  directories: $TRAVIS_BUILD_DIR/packrat/
  # PhantomJS
  #- travis_phantomjs

#cache:
  # Main R library
#  $TRAVIS_BUILD_DIR/packrat/
#  packages: true
#  directories:
    # Packrat packages
    #- packrat/lib
    # PhantomJS
    #- travis_phantomjs
    #$TRAVIS_BUILD_DIR/packrat/

# Install PhantomJS (if not cached)
before_install:
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "hash -r"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
  - "phantomjs --version"

script:
  - R -f run_tests.R
  
  
