app <- ShinyDriver$new("../", loadTimeout = 1e+05)
app$snapshotInit("mytest")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(side = "Upload")
app$snapshot()
app$uploadFile(`datafile-file` = c("All_topTableAll.csv", "TOXA_TELL_MA0020_AllChip_pData.csv", "TOXA_TELL_MA0020_AllChip_WorkingSet.csv"))
app$setInputs(pval1 = 0.03)
app$snapshot()
app$setInputs(volcfc = 3)
app$setInputs(volcfc = 2)
app$setInputs(volcpval = 0.01)
app$setInputs(topvolc = 5)
app$snapshot()
app$setInputs(side = "PCA")
app$setInputs(allIndividuspca = "click")
app$snapshot()
app$setInputs(pointsiize = 5)
app$setInputs(pointsiize = 4)
app$setInputs(label = FALSE)
app$setInputs(jitter = TRUE)
app$setInputs(ellipse = TRUE)
app$setInputs(dim2 = "3")
app$snapshot()
app$setInputs(side = "Venn")
app$setInputs(allCont = "click")
app$setInputs(fcvenn = 2.3)
app$setInputs(fcvenn = 3.1)
app$snapshot()
app$setInputs(fill = "red,blue,green,orange")
app$setInputs(dispvenn = "genes")
app$snapshot()
app$setInputs(Vennd = "vennbarplotpan")
app$setInputs(intscol = "LWT_CARBO-LWT_CTRL")
app$setInputs(intscol = c("LWT_CARBO-LWT_CTRL", "LKO_CTRL-LWT_CTRL"))
app$setInputs(topgenes = 25)
app$setInputs(topdegenes = "click")
app$snapshot()
app$setInputs(side = "Heatmap")
app$setInputs(allTests = "click")
app$setInputs(maxgen = 150)
app$setInputs(fc = 1.5)
app$snapshot()
app$setInputs(heatm = "click")
app$snapshot()
app$setInputs(indiv = c("LKO_CARBO", "LKO_CTRL", "LWT_CARBO"))
app$setInputs(toggleAdvanced = "click")
app$setInputs(toggleAdvancedcolors = "click")
app$setInputs(reactheat = TRUE)
app$snapshot()
app$snapshot()
app$setInputs(tabset25 = "test3")
app$snapshot()
