app <- ShinyDriver$new("../", loadTimeout = 1e+05 )
app$snapshotInit("mytest")

app$setInputs(sidebarCollapsed = FALSE)
app$uploadFile(file = c("All_topTableAll.csv", "TOXA_HEGU_MA0191_AllChip_pData.csv", "TOXA_HEGU_MA0191_AllChip_WorkingSet.csv"))
Sys.sleep(2)
app$setInputs(method = "None")
app$setInputs(pval1 = 0.01)
Sys.sleep(2)
app$snapshot()
app$setInputs(side = "PCA")
app$setInputs(indivpca = c("LKO_CTRL", "LKO_MCD ", "LWT_CTRL"))
app$setInputs(indivpca = c("LKO_CTRL", "LKO_MCD ", "LWT_CTRL", "LWT_MCD "))
app$snapshot()
app$setInputs(indivpca = c("LKO_CTRL", "LKO_MCD ", "LWT_CTRL"))
app$snapshot()
app$setInputs(colpca_1 = "#7570B3")
app$snapshot()
app$snapshot()
app$setInputs(side = "Venn")
app$setInputs(allCont = "click")
app$setInputs(dispvenn = "genes")
app$setInputs(intscol = "LWT_MCD-LWT_CTRL")
app$snapshot()
app$setInputs(side = "Heatmap")
Sys.sleep(2)
app$setInputs(test = "LKO_CTRL-LWT_CTRL")
app$setInputs(allTests = "click")
app$setInputs(fc = 2)
app$setInputs(pval = 0.04)
app$setInputs(heatm = "click")
Sys.sleep(2)
app$snapshot()
